export default [
  {
    id: 0,
    image: require('./takeAll.PNG'),
    live: 'https://react-takeall-app.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-ecommerce-app',
    name: 'Ecommerce App',
    exp: 'A shopping app that provides customer quality products for making your life enjoyable.',
    techs: ['React', 'ContextApi', 'Scss', 'Reducer'],
  },
  {
    id: 3,
    image: require('./github.PNG'),
    live: 'https://github-user-search-app-react.netlify.app/',
    repo: 'https://github.com/salperen-jpg/github-user-app',
    name: 'Github Users App',
    exp: "Github User App provides you user's information on the github platform such as followers,repos...",
    techs: ['ContextApi', 'React', 'Auth0', 'Scss'],
  },
  {
    id: 2,
    image: require('./todo.png'),
    live: 'https://react-todo-app-challenge.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-todo-app-redux',
    name: 'Todo App',
    exp: 'Todo app that can remind you your things that need to be done in some time interval .',
    techs: ['React', 'Redux', 'Styled Components'],
  },
  {
    id: 1,
    image: require('./weather.PNG'),
    live: 'https://weather-around-the-world.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-weather-api-app',
    name: 'Wheather App',
    exp: 'A Weather app that can allow you to display a present weather of specific location .',
    techs: ['React', 'ContextApi', 'Moment.js'],
  },

  {
    id: 4,
    image: require('./photoApp.PNG'),
    live: 'https://numerous-photo.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-numerous-photo-app',
    name: 'Numerous Photo',
    exp: 'Numerous photo allows you to find the spectacular photo for your need.',
    techs: ['React', 'UnSplash'],
  },
  {
    id: 5,
    image: require('./starbucks.PNG'),
    live: 'https://starbucks-clone-basics.netlify.app/',
    repo: 'https://github.com/salperen-jpg/starbucks-landing-page',
    name: 'Starbucks Clone',
    exp: 'Starbucks Clone.',
    techs: ['Html', 'Css', 'JavaScript'],
  },
  {
    id: 6,
    image: require('./overreacted.PNG'),
    live: 'https://react-overreacted-clone.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-overreacted-clone',
    name: 'Overreacted Clone',
    exp: 'This website is Overreacted web page clone which is created by Dan Abramov.',
    techs: ['React', 'Css'],
  },
  {
    id: 7,
    image: require('./feedback.PNG'),
    live: 'https://feedback-ui-react-app.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-feedback-ui-app',
    name: 'Feedback App',
    exp: 'It allows you to share your feedback with the others.',
    techs: ['React', 'Context Api', 'SCSS'],
  },
  {
    id: 8,
    image: require('./netflix.PNG'),
    live: 'https://netflix-home-page-clone.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-netflix-homepage-clone',
    name: 'Netflix Homepage Clone',
    exp: 'Netflix Homepage Clone',
    techs: ['React', 'CSS'],
  },
  {
    id: 9,
    image: require('./quiz.PNG'),
    live: 'https://react-general-knowledge-quiz.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-quiz-app',
    name: 'Quiz App',
    exp: 'General Knowledge Quiz is consist of three topics sport,history,politics and the  questions can go up to 50 questions.',
    techs: ['React', 'ContextApi'],
  },
  {
    id: 12,
    image: require('./disne.PNG'),
    live: 'https://react-disney-clone.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-disney-clone',
    name: 'Disney Clone',
    exp: 'Disney Clone',
    techs: ['React.js', 'ContextApi', 'SCSS'],
  },
  {
    id: 11,
    image: require('./photo.PNG'),
    live: 'https://vermillion-centaur-f5c881.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-photosnap-app',
    name: 'PhotoSnap',
    exp: 'PhotoSnap is where photographers can be able to share their stories and awesome shoots !',
    techs: ['HTML', 'SCSS', 'React'],
  },
  {
    id: 11,
    image: require('./tour.PNG'),
    live: 'https://world-tour-project.netlify.app/',
    repo: 'https://github.com/salperen-jpg/world-tour-project',
    name: 'World Tour',
    exp: 'The website of distinct places to see all over the world. Keep exploring!',
    techs: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    id: 10,
    image: require('./expense.PNG'),
    live: 'https://expence-tracker-app-react.netlify.app/',
    repo: 'https://github.com/salperen-jpg/react-expense-tracker',
    name: 'Expense Tracker App',
    exp: 'Expense tracker can help you to arrange your money in some time interval',
    techs: ['React', 'Css'],
  },
];
